#index:
#    path: /
#    controller: App\Controller\DefaultController::index
sabredav:
    path:     /dav{url}
    controller: App\Controller\SabreDavController::do
    requirements:
       url: '/?.*'